name: Welcome to my GitHub repo
on:
   issues:
    types: [opened]
permissions:
 issues: write
 contents: read

jobs:
 asses-issues:
  name: Welcome and label
  runs-on: ubuntu-latest
  steps:
   - name: Add thank you comment
   - uses: actions/github-script@v7
     with:
          script: |
            github.rest.issues.create comment({
              issue_number: context. issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
